#!/usr/bin/env bash
# Path B provisioning: the VM already exists (created in the OCI console), and
# you have its IP. Pushes ops/vm-bootstrap.sh over SSH, runs it, pulls back the
# app credentials, then smoke-tests the endpoint — all from this machine.
#
#   ops/provision-from-local.sh 129.153.1.2                 # user ubuntu, port 22
#   ops/provision-from-local.sh 129.153.1.2 ubuntu 2222     # custom SSH port
#   MINIO_DOMAIN=minio.example.com ops/provision-from-local.sh HOST [USER] [PORT]
set -euo pipefail

HOST="${1:?Usage: ops/provision-from-local.sh HOST [USER] [PORT]}"
USER="${2:-ubuntu}"
PORT="${3:-22}"
# Defaults to the keypair generated by ops/provision-oci.sh / ops/README.md;
# override with KUPPI_SSH_KEY=/path/to/key if you created your own.
IDENTITY="${KUPPI_SSH_KEY:-$HOME/.ssh/kuppi_oci}"
[ -f "$IDENTITY" ] || echo "NOTE: no SSH key at $IDENTITY — relying on ssh-agent/default keys."
SSH="ssh ${IDENTITY:+-i "$IDENTITY"} -o StrictHostKeyChecking=accept-new -o BatchMode=yes -p $PORT"
SCP="scp ${IDENTITY:+-i "$IDENTITY"} -o StrictHostKeyChecking=accept-new -P $PORT"
cd "$(dirname "$0")/.."

echo ">> pushing bootstrap script"
$SCP ops/vm-bootstrap.sh "$USER@$HOST:/tmp/"

echo ">> running bootstrap on $HOST (3-4 min; certificate issuance can take longer)"
$SSH "$USER@$HOST" \
  "MINIO_DOMAIN='${MINIO_DOMAIN:-}' sudo -E bash /tmp/vm-bootstrap.sh"

echo ">> pulling app credentials into ./.kuppi-s3-credentials.env (git-ignored)"
$SSH "$USER@$HOST" "sudo cat /root/kuppi-s3-credentials.env" > .kuppi-s3-credentials.env
chmod 600 .kuppi-s3-credentials.env

echo ">> smoke test against the new endpoint"
node ops/smoke-test.mjs .kuppi-s3-credentials.env || echo "NOTE: smoke test could not reach the endpoint from here (DNS/TLS for the domain). Re-run it once the domain resolves: node ops/smoke-test.mjs .kuppi-s3-credentials.env"

cat <<EOF

Done. Next steps:
  1. Copy the S3_* values from .kuppi-s3-credentials.env into Vercel env vars.
  2. Redeploy, then run: node ops/migrate-vercel-blob.mjs   (see ops/README.md)
EOF
